### PR TITLE
[Feature] Addition of support to mirroring of the video capture

### PR DESCRIPTION
**Pull request by kodypeterson**
This adds a new feature to expose the ability to mirror the video capture stream. This does not change any default or existing behavior.

### CODE REVIEW

**Comment by ThibaultBee** [comment]
Oh sorry, I missed your PR.

On iOS, the front camera is always mirrored. I thought this was your requirement.

In what use case, do you have to mirror or not the video?

**Comment by kodypeterson** [comment]
@ThibaultBee Here is the write-up on explanation of the use-case 

https://github.com/ThibaultBee/StreamPack/issues/72#issuecomment-1646117630

**Comment by ThibaultBee** [comment]
As far as I understand, you just need to mirror front cameras which is already the case in this project (not on Android yet).

So, the addition of an API to enable/disable mirroring does not seem usefull. Am I missing something? Do you need what is in the PR?

If you don't need this API, I will close the PR (not merge it).

**Comment by ThibaultBee** [comment]
Rejected as we force the mirror for front camera now: see https://github.com/apivideo/api.video-swift-live-stream/blob/da9e8db7a1144f13bcae7ceea5708ade26e91a4a/Sources/ApiVideoLiveStream/ApiVideoLiveStream.swift#L294

**Pull request closed without merging**
